Art/urls.py
from django.urls import path
from . import views

app_name='arts'

urlpatterns = [
    path('conta', views.conta, name='conta'),
    path('', views.post_list, name='post_list'),
    path('MarketPlace/', views.MarketPlace, name='MarketPlace'),
    path('jobs/', views.JobsList, name='JobsList'),
    path('post/new/', views.post_new, name='post_new'),
    path('novaArte/', views.cadastrarArte, name = 'newArt'),
    path('comprar/<int:pk>/', views.comprarArte, name='comprarArte'),
    path('cadastrar/', views.cadastrarJob, name='cadastrarJob'),
    path('confirm/<int:pk>', views.confirmPurchase, name = 'confirm'),
    path('enviarMensagem/', views.EnviarEmail, name = 'enviarMensagem'),
    path('mensagemEnviada/', views.MensagemEnviada, name = 'mensagemEnviada')
]

ArtStation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Art.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/first/', views.first, name='first'),
    path('newquestion/', views.newquestion, name='newquestion'),
    path('newchoice/', views.newchoice, name='newchoice'),
    path('list/', views.list, name='list'),
    path('<int:pk>/edit/', views.editquestion, name='editquestion'),
    path('<int:pk>/delete/', views.deletequestion, name='deletequestion'),
    path('choices/list/', views.listchoices, name='listchoices'),
    path('choices/<int:pk>/edit/', views.editchoice, name='editchoice'),
    path('choices/<int:pk>/delete/', views.deletechoice, name='deletechoice'),
]

polls/models.py
from django.db import models
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from .models import Question, Choice

class questionForm(forms.ModelForm):
	
	class Meta:
		model = Question
		fields = ('question_text',); 
		labels = {
            'question_text': 'Question',
        }

class choiceForm(forms.ModelForm):
	
	class Meta:
		model = Choice
		fields = ('choice_text', 'votes', 'question');
		labels = {
            'choice_text': 'Opção',
            'votes': 'Numero de Votos',
            'question': 'Questão',
        }

polls/views.py
from django.shortcuts import render
from django.http import Http404  
from django.http import HttpResponseNotFound 
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.shortcuts import get_object_or_404, redirect
import operator
from django.urls import reverse
from .forms import questionForm, choiceForm
from datetime import datetime  
from django.contrib import messages 
from django.contrib.auth.decorators import user_passes_test

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def first(request, question_id):

	esc = Choice.objects.all().filter(question=question_id)
	ordered = sorted(esc, key=operator.attrgetter('votes'), reverse = True)
	first = ordered[0]
	return HttpResponse(first)

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
	})
	else:
		selected_choice.votes += 1
		selected_choice.save()
	return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

@user_passes_test(lambda u: u.is_superuser)
def newquestion(request):
        
	if request.method == "POST":
		form = questionForm(request.POST)
		if form.is_valid():
			question = form.save(commit=False)
			question.pub_date = datetime.now()
			question.save()
			messages.success(request, 'The question was save with success!')
	else:
		form = questionForm()

	return render(request, 'polls/formulario.html', {'form': form})

@user_passes_test(lambda u: u.is_superuser)
def newchoice(request):
        
	if request.method == "POST":
		form = choiceForm(request.POST)
		if form.is_valid():
			choice = form.save(commit=False)
			choice.save()
			messages.success(request, 'The option was save with success!')
	else:
		form = choiceForm()

	return render(request, 'polls/formulario.html', {'form': form})

def list(request):
	question = Question.objects.all()

	print(Question)
	return render(request, 'polls/listquestions.html', {'questions': question})

@user_passes_test(lambda u: u.is_superuser)
def editquestion(request, pk):
	question = get_object_or_404(Question, pk=pk)
	if request.method == "POST":
		form = questionForm(request.POST, instance=question)
		if form.is_valid():
			question = form.save(commit=False)
			question.save()
			messages.success(request, 'The question was edit with success!')
			return redirect('polls:list')
	else:
		form = questionForm(instance=question)
	return render(request, 'polls/formulario.html', {'form': form})

@user_passes_test(lambda u: u.is_superuser)
def deletequestion(request,pk):
	question = get_object_or_404(Question, pk=pk)
	question.delete()
	messages.success(request, 'The question was delete with success!')
	return redirect('polls:list')


def listchoices(request):
	choices = Choice.objects.all()
	return render(request, 'polls/listchoices.html', {'choices': choices})

@user_passes_test(lambda u: u.is_superuser)
def editchoice(request, pk):
	choice = get_object_or_404(Choice, pk=pk)
	if request.method == "POST":
		form = choiceForm(request.POST, instance=choice)
		if form.is_valid():
			choice = form.save(commit=False)
			choice.save()
			messages.success(request, 'The option was edit with success!')
			return redirect('polls:listchoices')
	else:
		form = choiceForm(instance=choice)
	return render(request, 'polls/formulario.html', {'form': form})

@user_passes_test(lambda u: u.is_superuser)
def deletechoice(request,pk):
	choice = get_object_or_404(Choice, pk=pk)
	choice.delete()
	messages.success(request, 'The option was delete with success!')
	return redirect('polls:listchoices')

polls/templates/polls/detail.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}

{% block conteudo %}

<div class=" mdl-cell mdl-cell--8-col mdl-shadow--2dp ">
            <div class="table mdl-color--white">
<h1>{{ question.question_text }}</h1>

{% if error_message %}

	<p><strong>{{ error_message }}</strong></p>

{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">

{% csrf_token %}
{% for choice in question.choice_set.all %}

    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />

{% endfor %}
	<input type="submit" value="Vote" />
	</form>
	</div>
	</div>

{% endblock %}

polls/templates/polls/formulario.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}
{% load crispy_forms_tags %}

{% block conteudo %}

<div class=" mdl-cell mdl-cell--8-col mdl-shadow--2dp ">
{% if messages %}
 	{% for message in messages %}
    	<p class="{{ message.tags }}">{{ message }}</p>
   	{% endfor %}
{% endif %}
<form method="POST" class="post-form">{% csrf_token %}
    {{ form|crispy }}
<button type="submit" class="btn btn-primary js-scroll-trigger mt-3">Save</button>
</form>
</div>

{% endblock %}

polls/templates/polls/index.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}

{% block conteudo %}

<div class=" mdl-cell mdl-cell--8-col mdl-shadow--2dp ">
<div class="table mdl-color--white">
{% if messages %}

 	{% for message in messages %}
    	 <p class="{{ message.tags }}">{{ message }}</p>
   	{% endfor %}
{% endif %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>
</div>
{% endblock %}

polls/templates/polls/listchoices.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}

{% block conteudo %}
{% if messages %}

           {% for message in messages %}
              <p class="{{ message.tags }}">{{ message }}</p>
             {% endfor %}
        {% endif %}

	 <div class=" mdl-cell mdl-cell--8-col">
          <div class="table mdl-color--white">
            <table class="mdl-data-table mdl-js-data-table" width="100%" >
               <thead>
                  <tr>
                <th class="mdl-data-table__cell--non-numeric ">id</th>
                  <th>Conteudo</th>
                  <th>Pergunta</th>
                   <th>Opções</th>
                </tr>
             </thead>
              <tbody>

              {% for choice in choices%}

                <tr>
                 <td class="mdl-data-table__cell--non-numeric">{{choice.pk}}</td>
                 <td>{{choice.question}}</td>
                   <td>{{choice.choice_text}}</td>
                  <td>
                    <a class="mdl-navigation__link" href= "{% url 'polls:editchoice' pk=choice.pk %}"><i class="material-icons" role="presentation">create</i></a>
                   	<a class="mdl-navigation__link" href= "{% url 'polls:deletechoice' pk=choice.pk %}"><i class="material-icons" role="presentation">delete</i></a>
                  </td>
                </tr>

                {%endfor%}

              </tbody>
            </table>
            </div>
          </div>

{% endblock %}

polls/templates/polls/listquestions.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}

{% block conteudo %}
{% if messages %}

  {% for message in messages %}
    <p class="{{ message.tags }}">{{ message }}</p>
  {% endfor %}
{% endif %}

<div class=" mdl-cell mdl-cell--8-col ">
<div class="table mdl-color--white">
<table class="mdl-data-table mdl-js-data-table  mdl-shadow--2dp " width="100%" >
<thead>
<tr>
<th class="mdl-data-table__cell--non-numeric ">id</th>
<th>Pergunta</th>
<th>Opções</th>
</tr>
</thead>
<tbody>

{% for question in questions%}

  <tr>
  <td class="mdl-data-table__cell--non-numeric">{{question.pk}}</td>
  <td>{{question.question_text}}</td>
  <td>
  <a class="mdl-navigation__link" href= "{% url 'polls:editquestion' pk=question.pk %}"><i class="material-icons" role="presentation">create</i></a>
  <a class="mdl-navigation__link" href= "{% url 'polls:deletequestion' pk=question.pk %}"><i class="material-icons" role="presentation">delete</i></a>
  </td>
  </tr>

{%endfor%}

 </tbody>
</table>
</div>
</div>

{% endblock %}

polls/templates/polls/results.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}

{% block conteudo %}
{% if messages %}

 	{% for message in messages %}

    	<p class="{{ message.tags }}">{{ message }}</p>
   	{% endfor %}
   	
{% endif %}
<div class=" mdl-cell mdl-cell--8-col mdl-shadow--2dp ">
<div class="table mdl-color--white">
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}

    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>

{% endfor %}
</ul>
</div>
</div>

{% endblock %}