Art/urls.py
from django.urls import path
from . import views

app_name='arts'

urlpatterns = [
    path('conta', views.conta, name='conta'),
    path('', views.post_list, name='post_list'),
    path('MarketPlace/', views.MarketPlace, name='MarketPlace'),
    path('jobs/', views.JobsList, name='JobsList'),
    path('post/new/', views.post_new, name='post_new'),
    path('novaArte/', views.cadastrarArte, name = 'newArt'),
    path('comprar/<int:pk>/', views.comprarArte, name='comprarArte'),
    path('cadastrar/', views.cadastrarJob, name='cadastrarJob'),
    path('confirm/<int:pk>', views.confirmPurchase, name = 'confirm'),
    path('enviarMensagem/', views.EnviarEmail, name = 'enviarMensagem'),
    path('mensagemEnviada/', views.MensagemEnviada, name = 'mensagemEnviada')
]

ArtStation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Art.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'contas'

urlpatterns = [
	path('signup/', views.SignUp.as_view(), name='signup'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/first/', views.first, name='first'),
    path('newquestion/', views.newquestion, name='newquestion'),
    path('newchoice/', views.newchoice, name='newchoice'),
    path('list/', views.list, name='list'),
    path('<int:pk>/edit/', views.editquestion, name='editquestion'),
    path('<int:pk>/delete/', views.deletequestion, name='deletequestion'),
    path('choices/list/', views.listchoices, name='listchoices'),
    path('choices/<int:pk>/edit/', views.editchoice, name='editchoice'),
    path('choices/<int:pk>/delete/', views.deletechoice, name='deletechoice'),
]

templates/startbootstrap-grayscale-gh-pages/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="he Showcase Platform for Art & Design">
  <meta name="author" content="Evelin Karpavicius">

  <title>ArtStation</title>

  <!-- Bootstrap core CSS -->
 
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'css/grayscale.min.css' %}">

</head>

<body id="page-top">

{% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
</button>
      <li class="{{ message.tags }}" style="font-size: 20px">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'arts:post_list' %}">ArtStation</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#marketPlace">MarketPlace</a>
          </li>
          {% if request.user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'arts:newArt' %}">Register</a>
          </li>
          {% endif %}
          <li class="nav-item">
            {% if request.user.is_superuser %}
              <a class="nav-link js-scroll-trigger" href="{% url 'arts:cadastrarJob'%}">Jobs</a>
            {% else %}  
              <a class="nav-link js-scroll-trigger" href="{% url 'arts:JobsList'%}">Jobs</a>
            {% endif %}
            
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#signup">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->
  <header class="masthead">
    <div class="container d-flex h-100 align-items-center">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 text-uppercase"><a href = "{% url 'arts:post_list' %}">ArtStation</a></h1>
        <h2 class="text-white-50 mx-auto mt-2 mb-5">The Showcase Platform for Art & Design</h2>
        {% if not user.is_authenticated %}
        <a href="{%url 'contas:signup'%}" class="btn btn-primary js-scroll-trigger">Sign Up</a>
        <a href="{%url 'login'%}" class="btn btn-primary js-scroll-trigger">Login</a>

        {% else %}
        <a href="{%url 'logout'%}" class="btn btn-primary js-scroll-trigger">LogOut</a>
        {% endif %}
      </div>
    </div>
  </header>

  <!-- About Section -->
  <section id="about" class="about-section text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2 class="text-white mb-4">Showcase your portfolio</h2>
          <p class="text-white-50">ArtStation provides you with a simple, yet powerful way to show your art and seen by the right people in the industry. It's super fast and sleek. Add your work and production experience.</p>
        </div>
      </div>
      <img src="img/ipad.png" class="img-fluid" alt="">
    </div>
  </section>

  <!-- Projects Section -->
  <section id="marketPlace" class="projects-section bg-light">
    <div class="container">

      <!-- Featured Project Row -->
      <div class="row align-items-center no-gutters mb-4 mb-lg-5">
        <div class="col-xl-8 col-lg-7">
          <img class="img-fluid mb-3 mb-lg-0" src="img/bg-masthead.jpg" alt="">
        </div>
        <div class="col-xl-4 col-lg-5">
          <div class="featured-text text-center text-lg-left">
            <h4>Resources for Artists</h4>
            <p class="text-black-50 mb-0">Your portfolio needs to be on ArtStation.</p>
            {% if user.is_authenticated %}
              <a href="{% url 'polls:newquestion' %}">New Question</a>
              <a href="{% url 'polls:newchoice' %}">New Option</a>
              <a href="{% url 'polls:list' %}">List Questions</a>
              <a href="{% url 'polls:listchoices' %}">List Choises</a>
            {% endif %}
            <a href="{% url 'polls:index' %}">Polls</a>
          </div>
        </div>
      </div>

      <!-- Project One Row -->
        {% block conteudo %}
         {% endblock %}

    </div>
  </section>

  <!-- Signup Section -->
  <section id="signup" class="signup-section">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 mx-auto text-center">

          <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
          <h2 class="text-white mb-5">Subscribe to receive updates!</h2>

          <form class="form-inline d-flex">
            <input type="email" class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" id="inputEmail" placeholder="Enter email address...">
            <button type="submit" class="btn btn-primary mx-auto">Subscribe</button>
          </form>

        </div>
      </div>
    </div>
  </section>

  <!-- Contact Section -->
  <section class="contact-section bg-black">
    <div class="container">

      <div class="row">

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-map-marked-alt text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Mobile App</h4>
              <hr class="my-4">
              <div class="small text-black-50"><a href="https://apps.apple.com/us/app/artstation-app/id924645286">Download on the App Store</a></div>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-envelope text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Mobile App</h4>
              <hr class="my-4">
              <div class="small text-black-50">
               <div class="small text-black-50"><a href="https://play.google.com/store/apps/details?id=com.ballistiq.artstation">Get it on Google Play</a></div>
            </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="social d-flex justify-content-center">
        <a href="https://twitter.com/artstationhq" class="mx-2">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="https://www.facebook.com/artstationhq" class="mx-2">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="https://www.instagram.com/artstationhq/" class="mx-2">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="https://github.com/Karpavicius/ArtStation" class="mx-2">
          <i class="fab fa-github"></i>
        </a>
         <a href="{%url 'arts:enviarMensagem'%}" class="mx-2">
           <i class="fas fa-envelope text-primary mb-2"></i>
         </a>
      </div>

    </div>
  </section>

  <!-- Footer -->
  <footer class="bg-black small text-center text-white-50">
    <div class="container">
    	<h5>Template by: Blackrock Digital -  David Miller</h5>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
 

    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


  <!-- Plugin JavaScript -->
  
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/grayscale.min.js' %}"></script>

</body>

</html>