Art/urls.py
from django.urls import path
from . import views

app_name='arts'

urlpatterns = [
    path('conta', views.conta, name='conta'),
    path('', views.post_list, name='post_list'),
    path('MarketPlace/', views.MarketPlace, name='MarketPlace'),
    path('jobs/', views.JobsList, name='JobsList'),
    path('post/new/', views.post_new, name='post_new'),
    path('novaArte/', views.cadastrarArte, name = 'newArt'),
    path('comprar/<int:pk>/', views.comprarArte, name='comprarArte'),
    path('cadastrar/', views.cadastrarJob, name='cadastrarJob'),
    path('confirm/<int:pk>', views.confirmPurchase, name = 'confirm'),
    path('enviarMensagem/', views.EnviarEmail, name = 'enviarMensagem'),
    path('mensagemEnviada/', views.MensagemEnviada, name = 'mensagemEnviada')
]

ArtStation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Art.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Art/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Artes(models.Model):
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name = 'artistas')
    artistas = models.CharField(max_length=100)
    titulo = models.CharField('Title',max_length=200)
    descricao = models.TextField('Discription')
    imagem = models.ImageField('Image', upload_to='images/', blank=True, default=None)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    comprador = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name = 'comprador', blank=True, null=True, default=None)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.titulo

class Usuario(models.Model):
    nome = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.nome

class Jobs(models.Model):
    empresa = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nome = models.CharField('Name',max_length=200)
    local = models.TextField('Location')
    imagem = models.ImageField('Image', upload_to='images/', blank=True, default=None)
    vagas = models.TextField('Jobs Open')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

MarketPlace/models.py
from django.db import models
from django.conf import settings

class carrinho(models.Model):
	user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
	desenhos=models.ManyToMany

Art/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Reset

from .models import Post, Artes, Usuario, Jobs

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Row(
                Column('emissor', css_class='form-group col-md-6 col-sm-3'),
                Column('assunto', css_class='form-group col-md-6 col-sm-3'),
                css_class='form-row'
            ),
            'msg'
        )
        self.helper.add_input(Submit('submit', 'Enviar'))
        self.helper.add_input(Reset('reset', 'Limpar', css_class='btn-danger float-right'))


class ArteForm(forms.ModelForm):

    class Meta:
        model = Artes
        fields = ('titulo', 'artistas','descricao', 'imagem')

    def __init__(self, *args, **kwargs):
        super(ArteForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
       
        self.helper.add_input(Submit('submit', 'Enviar'))
        self.helper.add_input(Reset('reset', 'Limpar', css_class='btn-danger float-right'))

class UserForm(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ('nome',)

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
       
        self.helper.add_input(Submit('submit', 'Enviar'))
        self.helper.add_input(Reset('reset', 'Limpar', css_class='btn-danger float-right'))

class JobsForms(forms.ModelForm):

    class Meta:
        model = Jobs
        fields = ('nome', 'local', 'imagem', 'vagas')

    def __init__(self, *args, **kwargs):
        super(JobsForms, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
       
        self.helper.add_input(Submit('submit', 'Enviar'))
        self.helper.add_input(Reset('reset', 'Limpar', css_class='btn-danger float-right'))

class MensagemForms(forms.Form):
    emissor = forms.EmailField(required=True, label='Remetente')
    assunto = forms.CharField(required=True)
    msg = forms.CharField(widget=forms.Textarea, label='Mensagem')
    def __init__(self, *args, **kwargs):
        super(MensagemForms, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Row(
                Column('emissor', css_class='form-group col-md-6'),
                Column('assunto', css_class='form-group col-md-6'),
                css_class='form-row'
            ),
            'msg'
        )
        self.helper.add_input(Submit('submit', 'Enviar'))
        self.helper.add_input(Reset('reset', 'Limpar', css_class='btn-danger float-right'))

Art/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post, Artes, Jobs
from django.shortcuts import render, get_object_or_404
from .forms import PostForm, ArteForm, JobsForms, MensagemForms
from django.shortcuts import redirect
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def conta(request):
    a = 2+2
    return JsonResponse(a)

@user_passes_test(lambda u: u.is_superuser)
def cadastrarArte(request):
    if request.method == "POST":
        form = ArteForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.autor = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('arts:post_list')
    else:
        form = ArteForm()
        return render(request, 'html/ArtForm.html', {'form': form})

@login_required
def comprarArte(request, pk):
    arte = Artes.objects.get(pk=pk)
    if arte.comprador == None:
        return render(request, 'html/Arte.html', {'arte':arte})
    return redirect('arts:post_list')

@login_required
def confirmPurchase(request, pk):
    arte = Artes.objects.get(pk=pk)

    if request.method == "POST":
        if arte.artistas == request.user:
            messages.info(request, 'You can not buy your own art!')
            return redirect('arts:post_list')
        if request.POST.get('email') == request.user.email:
            arte.comprador = request.user
            arte.save()
            print(request.user.email)
            try:
                send_mail('Purchace confimation','Email send. Thank you!', ['evelinksantos@gmail.com'], [request.user.email])
                messages.success(request,'Thank you for buying on ArtStation! ')
            except BadHeaderError:
                return HttpResponse("Error")
        else:
             messages.warning(request,'Email did not match')
    return redirect('arts:post_list')


@user_passes_test(lambda u: u.is_superuser)
def cadastrarJob(request):
    if request.method == "POST":
        form = JobsForms(request.POST, request.FILES)
        if form.is_valid():
            jobs = form.save(commit=False)
            jobs.empresa = request.user
            jobs.published_date = timezone.now()
            jobs.save()
            return redirect('arts:JobsList')
    else:
        form = JobsForms()
        return render(request, 'html/JobsForms.html', {'form': form})

def post_list(request):
    posts = Artes.objects.filter(published_date__lte=timezone.now(), comprador = None).order_by('published_date')
    return render(request, 'html/ArtList.html', {'posts': posts})

def MarketPlace(request):
    marketplace = Artes.objects.filter(comprador = 'null')
    return render(request, 'html/MarketPlace.html', {'marketPlace': marketplace})

def JobsList(request):
    jobs = Jobs.objects.all()
    return render(request, 'html/Jobs.html', {'Jobs': jobs})

@login_required
def post_new(request):
    if request.method == "POST":
        form = ArteForm(request.POST, request.FILES)
    
        if form.is_valid():
            post = form.save(commit=False)
            post.artistas = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('arts:post_list')
    else:
        form = ArteForm()
    return render(request, 'html/post_edit.html', {'form': form})

@login_required
def EnviarEmail(request):
    mensagemForm = MensagemForms()
    if request.method == "POST":
        try:
            send_mail('Menssage',mensagemForm.mensagem, [mensagemForm.emissor], ['evelinksantos@gmail.com'])
        except BadHeaderError:
            return HttpResponse("Error")
        return redirect()
    return render(request, 'html/formEmail.html', {'email': mensagemForm})

@login_required
def EnviarEmail(request):
    if request.method == 'GET':
        email_form = MensagemForms()
    else:
        email_form = MensagemForms(request.POST)
        if email_form.is_valid():
            emissor = email_form.cleaned_data['emissor']
            assunto = email_form.cleaned_data['assunto']
            msg = email_form.cleaned_data['msg']

            try:
                send_mail(assunto, msg, emissor, ['evelinksantos@gmail.com'])
            except BadHeaderError:
                return render(request, 'html/formEmail.html', {'form': email_form})
            return redirect('MensagemEnviada')
    return render(request, 'html/formEmail.html', {'form': email_form})

def MensagemEnviada(request):
    return render(request, 'html/mensagemObrigado')

Art/templates/html/ArtForm.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}
{% load crispy_forms_tags %}

{% block conteudo %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-primary js-scroll-trigger mt-3">Submit</button>

    </form>
{% endblock conteudo %}

Art/templates/html/ArtList.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}
{% load static %}

     {% block conteudo %} 
     {%for post in posts%}
       <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
        {% if post.imagem %}
        <div class="col-lg-6">
          <img class="img-fluid" src="{{post.imagem.url}}" alt="">
        </div>
        {%endif%}
        <div class="col-lg-6">
          <div class="bg-black text-center h-100 project">
            <div class="d-flex h-100">
              <div class="project-text w-100 my-auto text-center text-lg-left">
                <h4 class="text-white">{{post.titulo}}</h4>
                <p class="mb-0 text-white-50">{{post.descricao}}</p>
                <p class="mb-0 text-white-50 artisName" style="display: none;">Artista: {{post.artistas}}</p>
                <hr class="d-none d-lg-block mb-0 ml-0">
                <a href="{% url 'arts:comprarArte' pk=post.pk %}" class="btn btn-primary js-scroll-trigger mt-3">Buy</a>
              </div>
            </div>
          </div>
        </div>
      </div>

       <script type="text/javascript" src="{% static 'js/imagem.js' %}"></script>
       {%endfor%}
     {% endblock conteudo %}

Art/templates/html/Arte.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}
{% load static %}

     {% block conteudo %} 
     
      <p>{{arte.titulo}}</p>
      <p>{{arte.descricao}}</p>
      {% if arte.imagem %}
        <div class="col-lg-6">
          <img class="img-fluid" src="{{arte.imagem.url}}" alt="">
        </div>
        {%endif%}

      <button id="confirmButton">Confirm Purchase</button>
      <div id="confirm" style="display: none;">
          <form method="POST" action="/confirm/{{arte.pk}}">
            {% csrf_token %}
          <p>Enter your email</p>
          <input type="text" name="email" id="email">
          <button type="submit" >Sent</button>
        </form>
      </div>
 <script type="text/javascript" src="{% static 'js/confirmPurchase.js' %}"></script>
     
     {% endblock %}

Art/templates/html/Jobs.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}

{% block conteudo %}
    {% for job in Jobs %}
    	 <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
        {% if job.imagem %}
        <div class="col-lg-6">
          <img class="img-fluid" src="{{job.imagem.url}}" alt="">
        </div>
        {%endif%}
        <div class="col-lg-6">
          <div class="bg-black text-center h-100 project">
            <div class="d-flex h-100">
              <div class="project-text w-100 my-auto text-center text-lg-left">
                <h4 class="text-white">{{job.nome}}</h4>
                <p class="mb-0 text-white-50">{{job.local}}</p>
                <p class="mb-0 text-white-50">{{job.vagas}}</p>
                <p class="mb-0 text-white-50">{{job.empresa}}</p>
                <hr class="d-none d-lg-block mb-0 ml-0">
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
{% endblock conteudo %}

Art/templates/html/JobsForms.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}
{% load crispy_forms_tags %}

{% block conteudo %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form|crispy }}

        <button type="submit" class="btn btn-primary js-scroll-trigger mt-3">Submit</button>

    </form>
{% endblock conteudo %}

Art/templates/html/MarketPlace.html
<!DOCTYPE html>
{% load static %}
<html lang="en-us">
<head>
	<title>ArtStation - MarketPlace</title>
</head>
<body>
	<article>
		{% for arte in marketPlace %}
			<p>{{arte.titulo}}</p>
			<p>{{arte.descricao}}</p>
			<a href="{% url 'arts:comprarArte' pk=arte.pk %}">Buy</a>
		{% endfor %}
	</article>
</body>
</html>

Art/templates/html/art_list.html
{% extends 'html/post_list.html' %}
{% load staticfiles %}

{% block conteudo %}
    <div class="post">
        {%for post in posts%}
        	{% if post.imagem%}
        	<img src="{{post.imagem.url}}" alt=""/>
        	{%endif%}

        {%endfor%}
    </div>
{% endblock conteudo %}

Art/templates/html/formEmail.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}

{% load crispy_forms_tags %}

{% block conteudo %}
    {% crispy form %}
{% endblock %}

Art/templates/html/mensagemObrigado.html
{% extends 'startbootstrap-grayscale-gh-pages/index.html' %}
{% load static %}

{% block conteudo %}
	<h4>Thank you for send a message!</h4>
{% endblock conteudo %}